function cuenta_data(sequelize,DataTypes){
    let alias = "Cuenta";

    let cols = {
        id:{type:DataTypes.INTEGER,primaryKey:true,autoIncrement:true,allowNull:false},
        fecha_ingreso_mail:{type:DataTypes.DATE,allowNull:false},
        pos_sunmi:{type:DataTypes.STRING(50),allowNull:false},
        /*id_tipo_alta:{type:DataTypes.INTEGER,allowNull:false},
        id_distribuidor:{type:DataTypes.INTEGER},*/
        distribuidor_nuevo:{type:DataTypes.STRING(50)},
        numero_cuenta:{type:DataTypes.STRING(50)},
        busqueda_x_id:{type:DataTypes.STRING(50)},
        /*id_etapa_1:{type:DataTypes.INTEGER},
        id_estado_1:{type:DataTypes.INTEGER},
        id_responsable_1:{type:DataTypes.INTEGER},
        id_etapa_2:{type:DataTypes.INTEGER},
        id_estado_2:{type:DataTypes.INTEGER},
        id_responsable_2:{type:DataTypes.INTEGER},
        id_etapa_3:{type:DataTypes.INTEGER},
        id_estado_3:{type:DataTypes.INTEGER},
        id_responsable_3:{type:DataTypes.INTEGER},
        id_etapa_4:{type:DataTypes.INTEGER},
        id_estado_4:{type:DataTypes.INTEGER},
        id_responsable_4:{type:DataTypes.INTEGER},
        id_etapa_5:{type:DataTypes.INTEGER},
        id_estado_5:{type:DataTypes.INTEGER},
        id_responsable_5:{type:DataTypes.INTEGER},
        id_etapa_6:{type:DataTypes.INTEGER},
        id_estado_6:{type:DataTypes.INTEGER},
        id_responsable_6:{type:DataTypes.INTEGER},
        id_etapa_7:{type:DataTypes.INTEGER},
        id_estado_7:{type:DataTypes.INTEGER},
        id_responsable_7:{type:DataTypes.INTEGER},
        id_etapa_8:{type:DataTypes.INTEGER},
        id_estado_8:{type:DataTypes.INTEGER},
        id_responsable_8:{type:DataTypes.INTEGER}*/
    };

    let config = {timestamps:false};

    let Cuenta = sequelize.define(alias,cols,config);

    Cuenta.associate = (modelos)=>{
        Cuenta.belongsTo(modelos.Distribuidor,{
            as:"CuentaDistribuidor",
            foreingKey:"CuentaDistribuidorId"
        }),
        Cuenta.belongsTo(modelos.Tipo_alta,{
            as:"CuentaTipoAlta",
            foreingKey:"CuentaTipoAltaId"
        }),
        Cuenta.belongsTo(modelos.Estado,{
            as:"CuentaEstado1",
            foreingKey:"CuentaEstado1Id"
        }),
        Cuenta.belongsTo(modelos.Etapa,{
            as:"CuentaEtapa1",
            foreingKey:"CuentaEtapa1Id"
        }),
        Cuenta.belongsTo(modelos.Responsable,{
            as:"CuentaResponsable1",
            foreingKey:"CuentaResponsable1Id"
        }),
        Cuenta.belongsTo(modelos.Estado,{
            as:"CuentaEstado2",
            foreingKey:"CuentaEstado2Id"
        }),
        Cuenta.belongsTo(modelos.Etapa,{
            as:"CuentaEtapa2",
            foreingKey:"CuentaEtapa2Id"
        }),
        Cuenta.belongsTo(modelos.Responsable,{
            as:"CuentaResponsable2",
            foreingKey:"CuentaResponsable2Id"
        }),
        Cuenta.belongsTo(modelos.Estado,{
            as:"CuentaEstado3",
            foreingKey:"CuentaEstado3Id"
        }),
        Cuenta.belongsTo(modelos.Etapa,{
            as:"CuentaEtapa3",
            foreingKey:"CuentaEtapa3Id"
        }),
        Cuenta.belongsTo(modelos.Responsable,{
            as:"CuentaResponsable3",
            foreingKey:"CuentaResponsable3Id"
        }),
        Cuenta.belongsTo(modelos.Estado,{
            as:"CuentaEstado4",
            foreingKey:"CuentaEstado4Id"
        }),
        Cuenta.belongsTo(modelos.Etapa,{
            as:"CuentaEtapa4",
            foreingKey:"CuentaEtapa4Id"
        }),
        Cuenta.belongsTo(modelos.Responsable,{
            as:"CuentaResponsable4",
            foreingKey:"CuentaResponsable4Id"
        }),
        Cuenta.belongsTo(modelos.Estado,{
            as:"CuentaEstado5",
            foreingKey:"CuentaEstado5Id"
        }),
        Cuenta.belongsTo(modelos.Etapa,{
            as:"CuentaEtapa5",
            foreingKey:"CuentaEtapa5Id"
        }),
        Cuenta.belongsTo(modelos.Responsable,{
            as:"CuentaResponsable5",
            foreingKey:"CuentaResponsable5Id"
        }),
        Cuenta.belongsTo(modelos.Estado,{
            as:"CuentaEstado6",
            foreingKey:"CuentaEstado6"
        }),
        Cuenta.belongsTo(modelos.Etapa,{
            as:"CuentaEtapa6",
            foreingKey:"CuentaEtapa6Id"
        }),
        Cuenta.belongsTo(modelos.Responsable,{
            as:"CuentaResponsable6",
            foreingKey:"CuentaResponsable6Id"
        }),
        Cuenta.belongsTo(modelos.Estado,{
            as:"CuentaEstado7",
            foreingKey:"CuentaEstado7Id"
        }),
        Cuenta.belongsTo(modelos.Etapa,{
            as:"CuentaEtapa7",
            foreingKey:"CuentaEtapa7Id"
        }),
        Cuenta.belongsTo(modelos.Responsable,{
            as:"CuentaResponsable7",
            foreingKey:"CuentaResponsable7Id"
        }),
        Cuenta.belongsTo(modelos.Estado,{
            as:"CuentaEstado8",
            foreingKey:"CuentaEstado8Id"
        }),
        Cuenta.belongsTo(modelos.Etapa,{
            as:"CuentaEtapa8",
            foreingKey:"CuentaEtapa8Id"
        }),
        Cuenta.belongsTo(modelos.Responsable,{
            as:"CuentaResponsable8",
            foreingKey:"CuentaResponsable8Id"
        })
    };
    return Cuenta;
};

module.exports = cuenta_data;